version: '3'
services:
  postgres:
    image: postgis/postgis
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
      
volumes:
  timescaledb_data:
